export const GET_ALL_RECIPES = 'GET_ALL_RECIPES';
export const GET_ALL_RECIPES_SUCCESS = 'GET_ALL_RECIPES_SUCCESS';
export const GET_ALL_RECIPES_ERR = 'GET_ALL_RECIPES_ERR';

export const REMOVE_RECIPE = 'REMOVE_RECIPE';
export const REMOVE_RECIPE_SUCCESS = 'REMOVE_RECIPE_SUCCESS';
export const REMOVE_RECIPE_ERR = 'REMOVE_RECIPE_ERR';

export const ADD_RECIPE = 'ADD_RECIPE';
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_ERR = 'ADD_RECIPE_ERR';

export const GET_RECIPE_BY_ID = 'GET_RECIPE_BY_ID';
export const GET_RECIPE_BY_ID_SUCCESS = 'GET_RECIPE_BY_ID_SUCCESS';
export const GET_RECIPE_BY_ID_ERR = 'GET_RECIPE_BY_ID_ERR';

export const EDIT_RECIPE = 'EDIT_RECIPE';
export const EDIT_RECIPE_SUCCESS = 'EDIT_RECIPE_SUCCESS';
export const EDIT_RECIPE_ERR = 'EDIT_RECIPE_ERR';